services:
  db_relacional:
    image: mysql:8.0
    container_name: mysql_its_math
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: demo
      MYSQL_DATABASE: its_murialdo
    ports:
      - "3307:3306"
    volumes:
      - its_rag_math_mysql_data:/var/lib/mysql

  app_tutor:
    build: .
    container_name: streamlit_its_math
    restart: always
    ports:
      - "8501:8501"
    depends_on:
      - db_relacional
    # AGREGA ESTAS DOS LÍNEAS AQUÍ ABAJO:
    volumes:
      - ./chroma_db:/app/chroma_db

volumes:
  its_rag_math_mysql_data: